// Generated by CoffeeScript 1.3.3
/*!PIM_PLUGIN
{ "name"    : "Chat Links"
, "version" : "0.0.4"
, "access"  : ["plugin","formatter","chatCollection"]
}
*/

var chatLinks, escapeHTML,
  _this = this;

escapeHTML = formatter.escapeHTML;

chatLinks = function(text, phase, meta) {
  var chat, chatId, chatName, matches, r, regexp;
  regexp = /\[chat ([0-9]+)\](?!\()/g;
  while (matches = regexp.exec(text)) {
    chatId = parseInt(matches[1]);
    chat = chatCollection.get(chatId);
    if (chat) {
      chatName = chat.get('topic');
    } else {
      chatName = "Chat " + chatId;
    }
    r = formatter.placeholder("<a href='/chat/" + chatId + "'>" + (escapeHTML(chatName)) + "</a>");
    text = text.substr(0, matches.index) + r + text.substr(matches.index + matches[0].length);
    matches.nextIndex = matches.index + r.length;
  }
  return text;
};

plugin.load = function() {
  formatter.add(formatter.PHASE_PLAIN, 80, chatLinks);
};

plugin.unload = function() {
  formatter.remove(formatter.PHASE_PLAIN, 80, chatLinks);
};
