// Generated by CoffeeScript 1.3.3
/*!PIM_PLUGIN
{
  "name": "Embed Tweet",
  "version": "0.0.6",
  "access": ["formatter","jsonp"],
  "dependencies": [
    "//platform.twitter.com/widgets.js"
  ]
}
*/

var delay, embedTweet, escapeHTML, renderTweet,
  _this = this;

delay = function(ms, cb) {
  return setTimeout(cb, ms);
};

escapeHTML = formatter.escapeHTML;

renderTweet = function(json) {
  var html;
  return html = "<blockquote class=\"twitter-tweet\">\n  <p>" + (escapeHTML(json.text)) + "</p>\n  &mdash; " + (escapeHTML(json.user.name)) + " (@" + (escapeHTML(json.user.screen_name)) + ") \n  <a href=\"https://twitter.com/" + (escapeHTML(json.user.screen_name)) + "/status/" + json.id_str + "\" data-datetime=\"" + (escapeHTML(json.created_at)) + "\">" + (escapeHTML(json.created_at)) + "</a>\n</blockquote>";
};

embedTweet = function(text, phase, meta) {
  var div, html, id, matches, r, regexp, tweetId, url;
  regexp = /\[tweet (?:https?:\/\/twitter.com\/[^\/]+\/status\/)?([0-9]+)\](?!\()/g;
  while (matches = regexp.exec(text)) {
    tweetId = matches[1];
    id = Math.random() * 100000000;
    id = "twitter_oembed_" + id;
    div = document.createElement('div');
    div.innerHTML = "Loading";
    url = "https://api.twitter.com/1/statuses/show/" + tweetId + ".json?callback=?";
    (function(id) {
      var _this = this;
      return jsonp(url, function(json) {
        var _ref;
        if ((_ref = document.getElementById(id)) != null) {
          _ref.innerHTML = renderTweet(json);
        }
        if (typeof twttr !== "undefined" && twttr !== null) {
          twttr.widgets.load();
        }
        delay(0, function() {
          return formatter.scrollBottom();
        });
      });
    })(id);
    html = "<div id='" + id + "'>Loading tweet " + (escapeHTML(tweetId)) + "...</div>";
    r = formatter.placeholder(html);
    text = text.substr(0, matches.index) + r + text.substr(matches.index + matches[0].length);
    regexp.lastIndex = matches.index + r.length;
  }
  return text;
};

plugin.load = function() {
  formatter.add(formatter.PHASE_PLAIN, 80, embedTweet);
};

plugin.unload = function() {
  formatter.remove(formatter.PHASE_PLAIN, 80, embedTweet);
};
