// Generated by CoffeeScript 1.3.3
/*!PIM_APP
{
  "name": "Embed Tweet",
  "version": "0.1.3",
  "access": ["app","formatter","jsonp","twttr"],
  "jsonp_urls": {
    "status":"https://api.twitter.com/1/statuses/show/{INT:TWEET_ID}.json?callback=?"
  },
  "dependencies": [
    "//platform.twitter.com/widgets.js"
  ]
}
---
This app allows you to embed tweets into chats using twitter's widget API.
To embed a tweet, simply type `[tweet #]` where `#` is the id of the tweet, or the URL to that individual tweet.
*/

var delay, embedTweet, escapeHTML, fetchTweet, renderTweet,
  _this = this;

delay = function(ms, cb) {
  return setTimeout(cb, ms);
};

escapeHTML = formatter.escapeHTML;

renderTweet = function(json) {
  var html;
  html = "<blockquote class=\"twitter-tweet\">\n  <p>" + (escapeHTML(json.text)) + "</p>\n  &mdash; " + (escapeHTML(json.user.name)) + " (@" + (escapeHTML(json.user.screen_name)) + ") \n  <a href=\"https://twitter.com/" + (escapeHTML(json.user.screen_name)) + "/status/" + json.id_str + "\" data-datetime=\"" + (escapeHTML(json.created_at)) + "\">" + (escapeHTML(json.created_at)) + "</a>\n</blockquote>";
  return html;
};

fetchTweet = function(tweetId, divId, promise) {
  jsonp("status", {
    TWEET_ID: tweetId
  }, function(json) {
    if (!(json != null)) {
      promise.fail("Failed to fetch tweet.");
    } else {
      promise.fulfil(renderTweet(json));
      delay(0, function() {
        twttr.loadWidgets();
        return delay(0, function() {
          return formatter.scrollBottom();
        });
      });
    }
  });
};

embedTweet = function(text, phase, meta) {
  return formatter.replaceMatches(text, /\[tweet (?:https?:\/\/twitter.com\/[^\/]+\/status\/)?([0-9]+)\](?!\()/g, function(matches) {
    var id, placeholder, promise, tweetId, _ref;
    tweetId = matches[1];
    id = Math.random() * 100000000;
    id = "twitter_oembed_" + id;
    _ref = formatter.promise('div', "Loading tweet " + tweetId + "..."), placeholder = _ref.placeholder, promise = _ref.promise;
    fetchTweet(tweetId, id, promise);
    return placeholder;
  });
};

app.render = function() {
  dom.pimFormat("To embed a tweet, simply type `[tweet #]` where `#` is the id of the tweet, or the URL to that individual tweet.");
};

app.load = function() {
  formatter.add(formatter.PHASE_PLAIN, 80, embedTweet);
};
